stages:
  - test
 
# --begin-- 如果项目没有lint可以删除这部分 --begin--
lint:
  stage: test
  image: node:latest
  cache:
    paths:
    - node_modules/
  before_script:
    - npm install
  script:
    - npm run lint
# --end-- 如果项目没有lint可以删除这部分 --end--
 
sonar-scan:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.16.42.19:9000/
    SONAR_PROJECT_VERSION: $CI_BUILD_ID
    SONAR_ANALYSIS_MODE: publish
  script:
    - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh
